name: Test Another Repo

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: PerfAI Action
        uses: P10-ai/Perf-Actions@v1.3
        with:
          openapi_spec_url: 'https://petstore.swagger.io/v2/swagger.yaml'
          description: Open API Spec File
          required: true
          default: 'https://petstore.swagger.io/v2/swagger.yaml'
