name: Create and publish a Docker image

on:
  push:
    branches:
      - main
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "{{ github.token }}"
      - name: echo a string
        run: echo "run a script"
      
      - name: multiline script
        run: |
          node -v
          npm -v
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: PerfAI Action
        uses: P10-ai/Perf-Actions@v1.9
        with:
          openapi_spec_url: "https://petstore.swagger.io/v2/swagger.yaml" 
