name: Test Another Repo

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: PerfAI Action
        uses: p10-ai/perf-engine@main
#        uses: ghcr.io/p10-ai/perf-engine
# ghcr.io/p10-ai/perf-engine        


#         with:
#           openapi_spec_url: 'https://petstore.swagger.io/v2/swagger.yaml'
#           description: Open API Spec File
#           required: false
#           default: 'https://petstore.swagger.io/v2/swagger.yaml'
