name: Test Another Repo

on:
  push:
    branches: ['main']
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}    

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
          
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: PerfAI Action
        uses: P10-ai/Perf-Actions@v1.3
#        uses: ghcr.io/p10-ai/perf-engine   


#         with:
#           openapi_spec_url: 'https://petstore.swagger.io/v2/swagger.yaml'
#           description: Open API Spec File
#           required: false
#           default: 'https://petstore.swagger.io/v2/swagger.yaml'
