name: Test Another Repo

on:
  push:
    branches: ['main']
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}    

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:   
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Use Docker image
        run: docker run docker.pkg.github.com/p10-ai/perf-Engine/perf-engine-image:latest
  
#       - name: PerfAI Action
#         uses: P10-ai/Perf-Actions@v1.3
#         with:
#           repository: p10-ai/perf-engine
          
        
#       - id: step2
#         run: echo ${{ steps.string.outputs.lowercase }} 
#        uses: ghcr.io/p10-ai/perf-engine   


#         with:
#           openapi_spec_url: 'https://petstore.swagger.io/v2/swagger.yaml'
#           description: Open API Spec File
#           required: false
#           default: 'https://petstore.swagger.io/v2/swagger.yaml'
